title: "<h2>HINF 5016</h2><h1>Natural Language Processing in Health<h1>"
description: "Jan. 6, 2025 - April 4, 2025, 5:15-8:15 pm East Time on Mondays | 
              WCMC Campus; TBD"
theme: jekyll-theme-cayman
