title: "HINF 5016: Natural Language Processing in Health"
description: "Jan. 10, 2024 - April 10, 2024, 5:15-8:15 pm East Time on Wednesdays | 
              WCMC Campus; 1300 Auditorium; A-950"
theme: jekyll-theme-cayman
